name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: gradle cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.gradle
          key: gradle-cache
      - name: Run checkstyle/test/build
        run: gradle build
